/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_MATERIAL_FILES           2
#define MMAP_MATERIAL_CHECKSUM        0xC3B4

enum MMAP_MATERIAL_LISTS {
    MMAP_MATERIAL_LOGO_1_SJPG = 0,        /*!< logo_1.sjpg */
    MMAP_MATERIAL_LOGO_2_SJPG = 1,        /*!< logo_2.sjpg */
};
