/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_EAF_FILES           1
#define MMAP_EAF_CHECKSUM        0xC4F3

enum MMAP_EAF_LISTS {
    MMAP_EAF_OSPREY_EAF = 0,        /*!< osprey.eaf */
};
